# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    #esi: true
    #fragments: true

    # http_client:
    #     scoped_clients:
    #         youtube.client:
    #             base_uri: 'https://www.googleapis.com/'  # URL de base
    #             headers:
    #                 Accept: 'application/json'
    #             query:
    #                 key: '%env(YOUTUBE_API_KEY)%'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
